### ISSUE TITLE
add .csv files

### ISSUE THREAD

**Issue by ca-vi** [wschroer/labile_DOC_supply_chain#1]
Having read "The Ocean's labile DOC supply chain" I am very grateful that you enable readers to reproduce your model. Your bootstrap method is nice and I would like to let it run on my machine. My aim here is to understand your inferences from the model output.
But the input data is missing here. Could you also put the three .csv files into this GIT repo ("PER.csv", "BGE.csv", "microGraz.csv")? I reckon the first two are summaries of the SupTablesS1S2S3 I found in the SupInfo but the third table is missing completely?! Also, I'd suggest adding them side by side with the script so that the _read.csv_-calls find the path. 
Thank you very much in advance!
Cheers
Carsten Lackner (PhD student @ TU Berlin)

**Comment by wschroer** [comment]
Hi Carsten,
I'm happy to hear that you have found found my model useful! Thank you for pointing out the missing data files, I have uploaded "PER.csv", "BGE.csv",  and "microGraz.csv" to the "labile_DOC_supply_chain" repository. 
Best of luck with your project and let me know if you have any other issues! 
Best,
William
